# Generated by Django 5.1.3 on 2025-05-27 04:34

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('legalUser', '0010_merge_0002_add_random_data_0009_attorney_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.IntegerField(help_text='Rating from 1 (worst) to 5 (best)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('review_text', models.TextField(blank=True, help_text='Optional written feedback', max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attorney', models.ForeignKey(help_text='Attorney being reviewed', on_delete=django.db.models.deletion.CASCADE, related_name='received_reviews', to='legalUser.user')),
                ('reviewer', models.ForeignKey(help_text='Client who is giving the review', on_delete=django.db.models.deletion.CASCADE, related_name='given_reviews', to='legalUser.user')),
            ],
            options={
                'unique_together': {('reviewer', 'attorney')},
            },
        ),
    ]
