from enum import Enum

class AttorneyExpertise(Enum):
    IMMIGRATION_LAW = "Immigration Law"
    EMPLOYMENT_LAW = "Employment Law"
    BANKRUPTCY_LAW = "Bankruptcy Law"
    ENVIRONMENTAL_LAW = "Environmental Law"
    HEALTHCARE_LAW = "Healthcare Law"
    INTERNATIONAL_LAW = "International Law"
    CONTRACT_LAW = "Contract Law"
    TORT_LAW = "Tort Law"
    CONSTITUTIONAL_LAW = "Constitutional Law"
    ADMINISTRATIVE_LAW = "Administrative Law"
    LABOR_LAW = "Labor Law"
    SECURITIES_LAW = "Securities Law"
    MERGERS_AND_ACQUISITIONS = "Mergers and Acquisitions"
    FAMILY_LAW = "Family Law"
    CRIMINAL_LAW = "Criminal Law"
    REAL_ESTATE_LAW = "Real Estate Law"
    INTELLECTUAL_PROPERTY_LAW = "Intellectual Property Law"
    TAX_LAW = "Tax Law"
    CIVIL_RIGHTS_LAW = "Civil Rights Law"
    ELDER_LAW = "Elder Law"
    ENTERTAINMENT_LAW = "Entertainment Law"
    SPORTS_LAW = "Sports Law"
    MILITARY_LAW = "Military Law"
    EDUCATION_LAW = "Education Law"
    ESTATE_PLANNING_LAW = "Estate Planning Law"
    PERSONAL_INJURY_LAW = "Personal Injury Law"
    AVIATION_LAW = "Aviation Law"
    MARITIME_LAW = "Maritime Law"
    ANTITRUST_LAW = "Antitrust Law"
    CYBER_LAW = "Cyber Law"
    INSURANCE_LAW = "Insurance Law"
    BANKING_LAW = "Banking Law"
    CONSUMER_PROTECTION_LAW = "Consumer Protection Law"
    DATA_PRIVACY_LAW = "Data Privacy Law"
    TECHNOLOGY_LAW = "Technology Law"
    MEDIA_LAW = "Media Law"
    HUMAN_RIGHTS_LAW = "Human Rights Law"
    FORECLOSURE_DEFENSE_LAW = "Foreclosure Defense Law"
    ASSET_PROTECTION_LAW = "Asset Protection Law"
    FOREIGN_INVESTMENT_LAW = "Foreign Investment Law"
    BIOTECHNOLOGY_LAW = "Biotechnology Law"
    PHARMACEUTICAL_LAW = "Pharmaceutical Law"
    OIL_AND_GAS_LAW = "Oil and Gas Law"
    ENERGY_LAW = "Energy Law"
    TRANSPORTATION_LAW = "Transportation Law"
    NONPROFIT_LAW = "Nonprofit Law"
    ANIMAL_LAW = "Animal Law"
    FRANCHISE_LAW = "Franchise Law"
    AGRICULTURAL_LAW = "Agricultural Law"
    FASHION_LAW = "Fashion Law"
    SPACE_LAW = "Space Law"
    ART_LAW = "Art Law"
    NATIVE_AMERICAN_LAW = "Native American Law"
    JUVENILE_LAW = "Juvenile Law"
    IMMIGRATION_COMPLIANCE_LAW = "Immigration Compliance Law"
    INFORMATION_SECURITY_LAW = "Information Security Law"
    E_COMMERCE_LAW = "E-Commerce Law"
    TRADE_LAW = "Trade Law"
    TRUSTS_AND_ESTATES_LAW = "Trusts and Estates Law"
    DRONE_LAW = "Drone Law"
    SOCIAL_SECURITY_DISABILITY_LAW = "Social Security Disability Law"
    DISABILITY_RIGHTS_LAW = "Disability Rights Law"
    INTERNET_LAW = "Internet Law"
    FORENSIC_LAW = "Forensic Law"
    WORKERS_COMPENSATION_LAW = "Workers' Compensation Law"

    @classmethod
    def choices(cls):
        return [(expertise.value, expertise.value) for expertise in cls]

    @classmethod
    def values(cls):
        return [expertise.value for expertise in cls]
