# Generated by Django 5.1.3 on 2025-05-20 14:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('legalUser', '0008_client_probono_rejected_reason_client_probono_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('document', models.TextField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_probono', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=True)),
                ('assigned_attorney', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='legalUser.attorney')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='legalUser.user')),
            ],
        ),
        migrations.CreateModel(
            name='CaseRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=255)),
                ('response_message', models.TextField(blank=True, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('attorney', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legalUser.attorney')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legalCase.case')),
            ],
        ),
    ]
