# Generated by Django 5.1.3 on 2025-05-21 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legalCase', '0001_initial'),
        ('legalUser', '0008_client_probono_rejected_reason_client_probono_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caserequest',
            name='attorney',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legalUser.user'),
        ),
    ]
