# Generated by Django 5.1.3 on 2025-05-21 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legalCase', '0002_alter_caserequest_attorney'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='assigned_attorney',
        ),
    ]
