# Generated by Django 5.1.3 on 2025-05-24 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legalCase', '0003_remove_case_assigned_attorney'),
        ('legalUser', '0009_attorney_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legalUser.user'),
        ),
    ]
