# Generated by Django 5.1.3 on 2025-05-17 08:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attorney',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('starting_price', models.FloatField(blank=True, null=True)),
                ('is_available', models.BooleanField(default=False)),
                ('offers_probono', models.BooleanField(default=False)),
                ('address', models.TextField(max_length=255)),
                ('rating', models.FloatField(default=0)),
                ('profile_completion', models.FloatField(default=0)),
                ('license_document', models.TextField(max_length=255)),
                ('is_approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Expertise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('client', 'Client'), ('attorney', 'Attorney')], max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('image', models.TextField(default=None, max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('institution', models.CharField(max_length=255)),
                ('degree', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('attorney', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legalUser.attorney')),
            ],
        ),
        migrations.CreateModel(
            name='AttorneyEducation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attorney', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legalUser.attorney')),
                ('education', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legalUser.education')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('years', models.IntegerField()),
                ('attorney', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legalUser.attorney')),
            ],
        ),
        migrations.CreateModel(
            name='AttorneyExperience',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attorney', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legalUser.attorney')),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legalUser.experience')),
            ],
        ),
        migrations.CreateModel(
            name='AttorneyExpertise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attorney', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legalUser.attorney')),
                ('expertise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legalUser.expertise')),
            ],
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('otp', models.CharField(max_length=6)),
                ('expired_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='otp_user', to='legalUser.user')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_probono', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='legalUser.user')),
            ],
        ),
        migrations.AddField(
            model_name='attorney',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='legalUser.user'),
        ),
    ]
