# Generated by Django 5.1.3 on 2025-05-18 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legalUser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='probono_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='probono_document',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='probono_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('attorney', 'Attorney'), ('admin', 'Admin')], max_length=255),
        ),
    ]
