# Generated by Django 5.1.3 on 2025-05-18 10:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legalUser', '0002_client_probono_approved_at_client_probono_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attorney',
            name='profile_completion',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
