# Generated by Django 5.1.3 on 2025-05-18 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legalUser', '0003_alter_attorney_profile_completion'),
    ]

    operations = [
        migrations.AddField(
            model_name='attorney',
            name='expertise',
            field=models.CharField(blank=True, choices=[('Immigration Law', 'Immigration Law'), ('Employment Law', 'Employment Law'), ('Bankruptcy Law', 'Bankruptcy Law'), ('Environmental Law', 'Environmental Law'), ('Healthcare Law', 'Healthcare Law'), ('International Law', 'International Law'), ('Contract Law', 'Contract Law'), ('Tort Law', 'Tort Law'), ('Constitutional Law', 'Constitutional Law'), ('Administrative Law', 'Administrative Law'), ('Labor Law', 'Labor Law'), ('Securities Law', 'Securities Law'), ('Mergers and Acquisitions', 'Mergers and Acquisitions'), ('Family Law', 'Family Law'), ('Criminal Law', 'Criminal Law'), ('Real Estate Law', 'Real Estate Law'), ('Intellectual Property Law', 'Intellectual Property Law'), ('Tax Law', 'Tax Law'), ('Civil Rights Law', 'Civil Rights Law'), ('Elder Law', 'Elder Law'), ('Entertainment Law', 'Entertainment Law'), ('Sports Law', 'Sports Law'), ('Military Law', 'Military Law'), ('Education Law', 'Education Law'), ('Estate Planning Law', 'Estate Planning Law'), ('Personal Injury Law', 'Personal Injury Law'), ('Aviation Law', 'Aviation Law'), ('Maritime Law', 'Maritime Law'), ('Antitrust Law', 'Antitrust Law'), ('Cyber Law', 'Cyber Law'), ('Insurance Law', 'Insurance Law'), ('Banking Law', 'Banking Law'), ('Consumer Protection Law', 'Consumer Protection Law'), ('Data Privacy Law', 'Data Privacy Law'), ('Technology Law', 'Technology Law'), ('Media Law', 'Media Law'), ('Human Rights Law', 'Human Rights Law'), ('Foreclosure Defense Law', 'Foreclosure Defense Law'), ('Asset Protection Law', 'Asset Protection Law'), ('Foreign Investment Law', 'Foreign Investment Law'), ('Biotechnology Law', 'Biotechnology Law'), ('Pharmaceutical Law', 'Pharmaceutical Law'), ('Oil and Gas Law', 'Oil and Gas Law'), ('Energy Law', 'Energy Law'), ('Transportation Law', 'Transportation Law'), ('Nonprofit Law', 'Nonprofit Law'), ('Animal Law', 'Animal Law'), ('Franchise Law', 'Franchise Law'), ('Agricultural Law', 'Agricultural Law'), ('Fashion Law', 'Fashion Law'), ('Space Law', 'Space Law'), ('Art Law', 'Art Law'), ('Native American Law', 'Native American Law'), ('Juvenile Law', 'Juvenile Law'), ('Immigration Compliance Law', 'Immigration Compliance Law'), ('Information Security Law', 'Information Security Law'), ('E-Commerce Law', 'E-Commerce Law'), ('Trade Law', 'Trade Law'), ('Trusts and Estates Law', 'Trusts and Estates Law'), ('Drone Law', 'Drone Law'), ('Social Security Disability Law', 'Social Security Disability Law'), ('Disability Rights Law', 'Disability Rights Law'), ('Internet Law', 'Internet Law'), ('Forensic Law', 'Forensic Law'), ("Workers' Compensation Law", "Workers' Compensation Law")], max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='AttorneyExpertise',
        ),
        migrations.DeleteModel(
            name='Expertise',
        ),
    ]
