# Generated by Django 5.1.3 on 2025-05-18 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legalUser', '0005_alter_attorney_expertise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attorney',
            name='expertise',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
