# Generated by Django 5.1.3 on 2025-05-19 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legalUser', '0006_alter_attorney_expertise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attorneyexperience',
            name='attorney',
        ),
        migrations.RemoveField(
            model_name='attorneyexperience',
            name='experience',
        ),
        migrations.DeleteModel(
            name='AttorneyEducation',
        ),
        migrations.DeleteModel(
            name='AttorneyExperience',
        ),
    ]
