# Generated by Django 5.1.3 on 2025-05-20 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legalUser', '0007_remove_attorneyexperience_attorney_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='probono_rejected_reason',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='probono_status',
            field=models.CharField(choices=[('not_applied', 'Not Applied'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='not_applied', max_length=255),
        ),
    ]
