# Generated by Django 5.1.3 on 2025-05-24 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legalUser', '0008_client_probono_rejected_reason_client_probono_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='attorney',
            name='bio',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
