# Generated by Django 5.1.3 on 2025-05-26 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legalUser', '0002_add_random_data'),
        ('legalUser', '0009_attorney_bio'),
    ]

    operations = [
    ]
