# Generated by Django 5.1.3 on 2025-05-22 11:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Constitutional', 'Constitutional'), ('Civil', 'Civil'), ('Criminal', 'Criminal'), ('Commercial', 'Commercial'), ('Labor', 'Labor'), ('Family', 'Family'), ('Investment', 'Investment'), ('Human Rights', 'Human Rights')], max_length=100)),
                ('jurisdiction', models.CharField(choices=[('Federal Government', 'Federal Government'), ('Addis Ababa Municipality', 'Addis Ababa Municipality'), ('Oromia Regional State', 'Oromia Regional State'), ('Tigray Regional State', 'Tigray Regional State'), ('Amhara Regional State', 'Amhara Regional State'), ("Southern Nations, Nationalities, and Peoples' Regional State (SNNPR)", "Southern Nations, Nationalities, and Peoples' Regional State (SNNPR)"), ('Sidama Regional State', 'Sidama Regional State'), ('Afar Regional State', 'Afar Regional State'), ('Somali Regional State', 'Somali Regional State'), ('Benishangul-Gumuz Regional State', 'Benishangul-Gumuz Regional State'), ('Gambela Regional State', 'Gambela Regional State'), ('Harari Regional State', 'Harari Regional State'), ('Dire Dawa City Administration', 'Dire Dawa City Administration')], max_length=100)),
                ('language', models.CharField(choices=[('Amharic', 'Amharic'), ('Oromo', 'Oromo'), ('Tigrinya', 'Tigrinya'), ('Somali', 'Somali'), ('Afar', 'Afar'), ('Sidamo', 'Sidamo'), ('Wolaytta', 'Wolaytta'), ('Gurage', 'Gurage'), ('Hadiyya', 'Hadiyya'), ('Gamo', 'Gamo'), ('Kaffa', 'Kaffa'), ('Harari', 'Harari'), ('Bench', 'Bench'), ('Sheko', 'Sheko'), ('Anuak', 'Anuak'), ('Nuer', 'Nuer'), ('Shanqella', 'Shanqella'), ('Konso', 'Konso'), ("Silt'e", "Silt'e"), ('Agaw', 'Agaw')], max_length=50)),
                ('proclamation_number', models.CharField(max_length=50)),
                ('publication_year', models.IntegerField()),
                ('document_url', models.URLField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-publication_year'],
            },
        ),
    ]
