# Generated by Django 5.1.3 on 2025-05-24 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legalLaw', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legaldocument',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='legaldocument',
            name='jurisdiction',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='legaldocument',
            name='language',
            field=models.CharField(max_length=50),
        ),
    ]
